name: ci

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Exécutez tous les jours à minuit UTC

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: olivier47
          password: dckr_pat_30qki9lRgzXyBCmkAD9h1uQNweM

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: olivier47/nextwebapp:latest, olivier47/nextwebapp:${{github.run_number}}
            
