name: Dependabot

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Exécutez tous les jours à minuit UTC

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker-compose build
          docker-compose up -d
          go test ./...

      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: olivier47/nextwebapp:latest, olivier47/nextwebapp:${{github.run_number}}
            
